export const PATHS = {
  LOGIN: "login",
  DASHBOARD: "dashboard",
  SPLASH: "splash", // 👈 added
  PERMITS: "permits",
  WHITELIST: "whitelist",
  PLATES: "plates",
  TRADELICENSES: "tradelicenses",
  PLEDGES: "pledges",
  INSPECTIONS: "inspections",
  FINES: "fines",
  PARKONIC: "parkonic",
  DISPUTE: "dispute",
  GENERAL: "general",
  ZONELINKING: "UserZoneLinking",
  SHIFTPLANNING: "ShiftPlanning",
};

export const FULL_PATHS = {
  ROOT: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  SPLASH: "/splash", // 👈 added
  PERMITS: "/permits",
  GENERAL: "/general",
  WHITELIST: "/whitelist",
  WHITELIST_PLATES: "/whitelist/plates",
  WHITELIST_TRADELICENSES: "/whitelist/tradelicenses",
  PLEDGES: "/pledges",
  INSPECTIONS: "/inspections",
  PARKONIC: "/parkonic",
  FINES: "/fines",
  HRMS: "/hrms",
  DISPUTE: "/dispute",
  TOWING: "/towing",
  TEAM: "/team",
  ANALYTICS: "/analytics",
  ZONELINKING: "/UserZoneLinking",
  SHIFTPLANNING: "/ShiftPlanning",
};