export const PATHS = {
  LOGIN: "login",
  DASHBOARD: "dashboard",
  SPLASH: "splash", // 👈 added
  PERMITS: "permits",
  WHITELIST: "whitelist",
  PLATES: "plates",
  TRADELICENSES: "tradelicenses",
  PLEDGES: "pledges",
  INSPECTIONS: "inspections",
  FINES: "fines",
  PARKONIC: "parkonic",
  DISPUTE: "dispute",
  GENERAL: "general",
  INSPECTOR_MANAGEMENT: "inspector-management",
  SUPERVISROR_MANGEMENT: "supervisor-management",
  SHIFTPLANNING: "ShiftPlanning",
};

export const FULL_PATHS = {
  ROOT: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  SPLASH: "/splash", // 👈 added
  PERMITS: "/permits",
  GENERAL: "/general",
  WHITELIST: "/whitelist",
  WHITELIST_PLATES: "/whitelist/plates",
  WHITELIST_TRADELICENSES: "/whitelist/tradelicenses",
  PLEDGES: "/pledges",
  INSPECTIONS: "/inspections",
  INSPECTIONS_OBSTACLES: "/inspections-obstacles",
  PARKONIC: "/parkonic",
  FINES: "/fines",
  HRMS: "/hrms",
  DISPUTE: "/dispute",
  SUPERVISROR_MANGEMENT: "/supervisor-management",
  LEAVE_MANGEMENT: "/leave-management",
  TOWING: "/towing",
  TEAM: "/team",
  TEAM_ASSESSMENT: "/team-assessment",
  ANALYTICS: "/analytics",
  INSPECTOR_MANAGEMENT: "/inspector-management",
  SHIFTPLANNING: "/ShiftPlanning",
};